# Generated by Django 2.1 on 2018-09-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('tel', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('sign', models.CharField(max_length=45)),
                ('job', models.CharField(max_length=45)),
            ],
        ),
    ]
