# Generated by Django 2.1 on 2018-09-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonweb', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
            ],
        ),
    ]
