# Generated by Django 2.1 on 2018-09-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonweb', '0003_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='econtent',
            field=models.TextField(default='moren'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='moren', max_length=45),
        ),
    ]
