# Generated by Django 2.1 on 2018-09-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonweb', '0004_auto_20180904_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.CharField(default='moren', max_length=45),
        ),
    ]
