# Generated by Django 2.1 on 2018-09-04 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonweb', '0005_question_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.CharField(default='moren', max_length=45),
        ),
    ]
