# Generated by Django 2.1 on 2018-09-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonweb', '0007_question_etype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='moren', max_length=45)),
                ('summary', models.CharField(default='moren', max_length=45)),
                ('author', models.CharField(default='moren', max_length=45)),
                ('time', models.CharField(default='moren', max_length=45)),
            ],
        ),
    ]
